"use client";

import React, { useEffect, useState } from "react";
import { Header } from "@/components/layout/header";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

interface Referral {
  _id: string;
  patientId: { _id: string; name: string; mrn: string };
  condition: string;
  confidence: number;
  severity: string;
  destination: string;
  distance: string;
  eta: string;
  status: string;
  createdAt: string;
}

const SEVERITY_STYLES: Record<string, string> = {
  critical: "bg-alert-red-light text-alert-red-dark",
  high: "bg-amber-light text-amber",
};

const STATUS_STYLES: Record<string, string> = {
  "pending": "bg-alert-red-light text-alert-red-dark",
  "dispatched": "bg-clinical-blue-light text-clinical-blue",
  "completed": "bg-success-bg text-success",
};

function formatDate(dateStr: string) {
  const d = new Date(dateStr);
  return d.toLocaleDateString("en-US", { month: "short", day: "2-digit", year: "numeric" });
}

export default function ReferralsPage() {
  const [referrals, setReferrals] = useState<Referral[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function load() {
      try {
        const res = await fetch("/api/referrals");
        if (res.ok) {
          const data = await res.json();
          setReferrals(data);
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    load();
  }, []);

  return (
    <>
      <Header title="Triage & Referral Manager" />
      <div className="flex-1 overflow-y-auto p-5 md:p-6">
        <div className="max-w-5xl mx-auto space-y-5">
          {loading ? (
            <div className="clinical-card p-12 flex flex-col items-center justify-center text-center">
              <div className="w-8 h-8 rounded-full border-2 border-clinical-blue border-t-transparent animate-spin mb-3" />
              <p className="text-sm text-outline">Loading referrals...</p>
            </div>
          ) : referrals.length === 0 ? (
            <div className="clinical-card p-12 flex flex-col items-center justify-center text-center border-dashed">
              <p className="text-sm font-medium text-on-surface-variant mb-1">No referrals active</p>
              <p className="text-xs text-outline">Emergency referrals generated by the AI will appear here.</p>
            </div>
          ) : (
            referrals.map((ref) => (
              <div key={ref._id} className={`clinical-card overflow-hidden ${ref.severity === "critical" ? "border-l-[3px] border-l-alert-red" : "border-l-[3px] border-l-amber"}`}>
                <div className="p-5">
                  <div className="flex flex-col md:flex-row md:items-start justify-between gap-4 mb-4">
                    <div>
                      <div className="flex items-center gap-2 mb-1">
                        <span className="font-heading text-base font-semibold">Patient: {ref.patientId?.name || "Unknown"}</span>
                        <Badge variant="secondary" className="text-[10px] font-mono">ID: {ref.patientId?.mrn || "N/A"}</Badge>
                      </div>
                      <p className="text-xs text-outline">AI Confidence: {ref.confidence}%</p>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className={`status-chip ${SEVERITY_STYLES[ref.severity] || ""}`}>
                        {ref.severity.toUpperCase()}
                      </span>
                      <span className={`status-chip ${STATUS_STYLES[ref.status] || ""}`}>
                        {ref.status.toUpperCase()}
                      </span>
                    </div>
                  </div>

                  <div className={`p-3 rounded-sm mb-4 ${ref.severity === "critical" ? "bg-alert-red-bg border border-alert-red/10" : "bg-amber-bg border border-amber/10"}`}>
                    <div className="flex items-center gap-2 mb-1">
                      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke={ref.severity === "critical" ? "#ba1a1a" : "#7c5800"} strokeWidth="2.5">
                        <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/>
                        <line x1="12" y1="9" x2="12" y2="13"/>
                        <line x1="12" y1="17" x2="12.01" y2="17"/>
                      </svg>
                      <span className={`text-sm font-semibold ${ref.severity === "critical" ? "text-alert-red" : "text-amber"}`}>{ref.condition}</span>
                    </div>
                  </div>

                  <div className="flex flex-col md:flex-row md:items-center justify-between gap-3">
                    <div className="flex items-center gap-4 text-xs text-on-surface-variant">
                      <span className="flex items-center gap-1.5">
                        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"/><circle cx="12" cy="10" r="3"/></svg>
                        {ref.destination}
                      </span>
                      <span>{ref.distance} &bull; Est. {ref.eta}</span>
                      <span>{formatDate(ref.createdAt)}</span>
                    </div>
                    <div className="flex gap-2">
                      <Button variant="outline" className="h-8 text-xs border-outline-variant">View Details</Button>
                      {ref.status === "pending" && (
                        <Button className="h-8 text-xs bg-alert-red text-white hover:bg-alert-red-dark">
                          Send Referral
                        </Button>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </>
  );
}
